language: objective-c

osx_image: xcode7.3.1

before_install:
  - gem install xcpretty
  - brew update
  - brew reinstall xctool
  - xcrun simctl list

env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
  - MODE=framework

script:
  - set -o pipefail && xcodebuild -project BerTlv.xcodeproj
    -scheme BerTlv
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGN_IDENTITY=""
    clean build | xcpretty -c
