language: objective-c

osx_image: xcode7.3

before_install:
  - gem install xcpretty
  - xcrun simctl list

script:
  - set -o pipefail && xcodebuild -project BerTlv.xcodeproj
    -scheme BerTlv
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGNING_REQUIRED=NO
    CODE_SIGN_IDENTITY=""
    clean build | xcpretty -c
